/**
 * SIH26189 - Heterogeneous Criminal-Network Intelligence Platform
 * DEMO DATASET - SINGLE SOURCE OF TRUTH
 *
 * CRITICAL NOTICE:
 * ALL DATA IS SYNTHETIC AND CREATED SOLELY FOR PROTOTYPE DEMONSTRATION.
 * No real persons, phone numbers, addresses, FIR numbers, or case histories are depicted.
 * Analytical indicators and priorities are illustrative and do not determine criminality or guilt.
 */

export const DISCLAIMER_TEXT =
  "DEMONSTRATION ENVIRONMENT: All entities, relationships, communications, locations, and case records are synthetic and created solely for prototype demonstration. Analytical metrics are illustrative and do not establish guilt or legal findings."

// ==========================================
// 1. ENTITIES (NORMALIZED HETEROGENEOUS DATA)
// ==========================================

export const entities = [
  // --- 10 SYNTHETIC PERSONS ---
  {
    id: 'P001',
    type: 'PERSON',
    name: 'Arjun Mehta',
    aliases: ['AJ', 'Mehta Transport'],
    status: 'ACTIVE',
    basePriority: 84,
    role: 'Logistics Fleet Coordinator',
    createdAt: '2026-06-12',
    description: 'Synthetic demonstration entity coordinating freight and transport logistics across northern hubs.',
    department: 'Fleet & Cargo Section'
  },
  {
    id: 'P002',
    type: 'PERSON',
    name: 'Rohit Sharma',
    aliases: ['Ro', 'Fleet Contractor'],
    status: 'ACTIVE',
    basePriority: 88,
    role: 'Primary Transport Contractor',
    createdAt: '2026-06-15',
    description: 'Synthetic demonstration subject managing inter-depot haulage vehicles and dispatch operations.',
    department: 'Commercial Transport Services'
  },
  {
    id: 'P003',
    type: 'PERSON',
    name: 'Sameer Khan',
    aliases: ['Sam', 'Inter-City Broker'],
    status: 'UNDER_REVIEW',
    basePriority: 92,
    role: 'Cross-Network Broker & Liaison',
    createdAt: '2026-05-20',
    description: 'Synthetic bridge entity linking commercial logistics operators with trading and financing partners.',
    department: 'Inter-Agency Liaison Group'
  },
  {
    id: 'P004',
    type: 'PERSON',
    name: 'Vikram Joshi',
    aliases: ['Vicky', 'Warehouse Lead'],
    status: 'ACTIVE',
    basePriority: 76,
    role: 'Terminal Operations Supervisor',
    createdAt: '2026-06-18',
    description: 'Synthetic demonstration operative supervising staging docks and heavy container vehicle assignments.',
    department: 'Terminal Cargo Control'
  },
  {
    id: 'P005',
    type: 'PERSON',
    name: 'Nikhil Verma',
    aliases: ['Nik', 'Escrow Handler'],
    status: 'ACTIVE',
    basePriority: 71,
    role: 'Financial Settlement Agent',
    createdAt: '2026-06-25',
    description: 'Synthetic subject facilitating invoices, accounts settlement, and escrow transactions.',
    department: 'Commercial Accounts & Settlement'
  },
  {
    id: 'P006',
    type: 'PERSON',
    name: 'Aman Singh',
    aliases: ['Monty', 'Driver Team Lead'],
    status: 'ACTIVE',
    basePriority: 68,
    role: 'Haulage Driver Coordinator',
    createdAt: '2026-07-01',
    description: 'Synthetic field operator responsible for night transport convoys and vehicle routing.',
    department: 'Night Fleet Division'
  },
  {
    id: 'P007',
    type: 'PERSON',
    name: 'Karan Rawat',
    aliases: ['KD', 'Transit Agent'],
    status: 'INACTIVE',
    basePriority: 54,
    role: 'Permit & Transit Liaison',
    createdAt: '2026-07-04',
    description: 'Synthetic administrative entity handling waybills, state transit permits, and toll clearances.',
    department: 'Regulatory Compliance Support'
  },
  {
    id: 'P008',
    type: 'PERSON',
    name: 'Mohit Saini',
    aliases: ['MS', 'Tech Handler'],
    status: 'UNDER_REVIEW',
    basePriority: 62,
    role: 'Telemetry & Radio Handler',
    createdAt: '2026-07-10',
    description: 'Synthetic technician monitoring GPS tracking modules and radio comms devices on transit assets.',
    department: 'Hardware Maintenance'
  },
  {
    id: 'P009',
    type: 'PERSON',
    name: 'Dev Malhotra',
    aliases: ['Dave', 'Trade Associate'],
    status: 'ACTIVE',
    basePriority: 59,
    role: 'Wholesale Trade Associate',
    createdAt: '2026-07-14',
    description: 'Synthetic demonstration partner in trade procurement and warehouse merchandise distribution.',
    department: 'Procurement Division'
  },
  {
    id: 'P010',
    type: 'PERSON',
    name: 'Rajat Kapoor',
    aliases: ['RK', 'Managing Director'],
    status: 'ACTIVE',
    basePriority: 79,
    role: 'Executive Director of Trading',
    createdAt: '2026-06-01',
    description: 'Synthetic executive supervising trading partnerships and commercial lease agreements.',
    department: 'Executive Governance'
  },

  // --- 8 SYNTHETIC PHONES ---
  {
    id: 'PH001',
    type: 'PHONE',
    name: '+91-98765-01001',
    aliases: ['Handset Alpha', 'Primary Comms 1'],
    status: 'ACTIVE',
    basePriority: 75,
    role: 'Secure Cellular Line',
    createdAt: '2026-06-10',
    description: 'Synthetic encrypted device associated with fleet coordination calls.',
    carrier: 'Synthetel Cellular',
    imei: '354920084711928'
  },
  {
    id: 'PH002',
    type: 'PHONE',
    name: '+91-98765-01002',
    aliases: ['Handset Bravo', 'Fleet Line 2'],
    status: 'ACTIVE',
    basePriority: 78,
    role: 'Operations Trunk Handset',
    createdAt: '2026-06-12',
    description: 'Synthetic cellular line linked to driver dispatch and terminal calls.',
    carrier: 'Synthetel Cellular',
    imei: '354920084711929'
  },
  {
    id: 'PH003',
    type: 'PHONE',
    name: '+91-98765-01003',
    aliases: ['Handset Charlie', 'Broker Bridge SIM'],
    status: 'ACTIVE',
    basePriority: 85,
    role: 'High-Volume Relay Line',
    createdAt: '2026-06-15',
    description: 'Synthetic dual-SIM handset observed in cross-cluster phone traffic.',
    carrier: 'Nexus Mobile',
    imei: '354920084711930'
  },
  {
    id: 'PH004',
    type: 'PHONE',
    name: '+91-98765-01004',
    aliases: ['Handset Delta', 'Warehouse Hotline'],
    status: 'ACTIVE',
    basePriority: 60,
    role: 'Depot Communication Line',
    createdAt: '2026-06-20',
    description: 'Synthetic landline-paired cellular terminal at freight terminal.',
    carrier: 'Nexus Mobile',
    imei: '354920084711931'
  },
  {
    id: 'PH005',
    type: 'PHONE',
    name: '+91-98765-01005',
    aliases: ['Handset Echo', 'Settlement Line'],
    status: 'ACTIVE',
    basePriority: 65,
    role: 'Escrow Comms Device',
    createdAt: '2026-06-22',
    description: 'Synthetic burner device used for financial confirmations.',
    carrier: 'Metro Wireless',
    imei: '354920084711932'
  },
  {
    id: 'PH006',
    type: 'PHONE',
    name: '+91-98765-01006',
    aliases: ['Handset Foxtrot', 'Transit Relay'],
    status: 'ACTIVE',
    basePriority: 55,
    role: 'Haulage Driver Terminal',
    createdAt: '2026-07-02',
    description: 'Synthetic satellite-capable vehicle unit in haulage truck cabin.',
    carrier: 'AeroComm Satellite',
    imei: '354920084711933'
  },
  {
    id: 'PH007',
    type: 'PHONE',
    name: '+91-98765-01007',
    aliases: ['Handset Golf', 'Field Radio'],
    status: 'INACTIVE',
    basePriority: 45,
    role: 'Standby Field Handset',
    createdAt: '2026-07-05',
    description: 'Synthetic dormant line with intermittent tower handshakes.',
    carrier: 'Metro Wireless',
    imei: '354920084711934'
  },
  {
    id: 'PH008',
    type: 'PHONE',
    name: '+91-98765-01008',
    aliases: ['Handset Hotel', 'Executive Line'],
    status: 'ACTIVE',
    basePriority: 70,
    role: 'Executive Voice Channel',
    createdAt: '2026-06-05',
    description: 'Synthetic private line registered to corporate headquarters.',
    carrier: 'Nexus Mobile',
    imei: '354920084711935'
  },

  // --- 6 SYNTHETIC LOCATIONS ---
  {
    id: 'LOC001',
    type: 'LOCATION',
    name: 'North Sector Warehouse Hub',
    aliases: ['Hub 12', 'Northern Terminal'],
    status: 'ACTIVE',
    basePriority: 72,
    role: 'Central Heavy Cargo Depot',
    createdAt: '2026-05-10',
    description: 'Synthetic storage facility featuring automated loading docks and weighbridges.',
    coordinates: '28.7041° N, 77.1025° E',
    zone: 'Northern Industrial Corridor'
  },
  {
    id: 'LOC002',
    type: 'LOCATION',
    name: 'Central Freight Terminal',
    aliases: ['Yard C', 'Interchange Yard'],
    status: 'ACTIVE',
    basePriority: 80,
    role: 'Multi-Modal Logistics Interchange',
    createdAt: '2026-05-12',
    description: 'Synthetic rail-road intermodal depot where multiple convoys converge.',
    coordinates: '28.6139° N, 77.2090° E',
    zone: 'Central Transit Hub'
  },
  {
    id: 'LOC003',
    type: 'LOCATION',
    name: 'Portview Logistics Park',
    aliases: ['Dockside Sector 4'],
    status: 'ACTIVE',
    basePriority: 64,
    role: 'Bonded Freight Warehouse',
    createdAt: '2026-05-15',
    description: 'Synthetic bonded warehouse facility for container storage and clearance.',
    coordinates: '28.5355° N, 77.3910° E',
    zone: 'East Industrial Zone'
  },
  {
    id: 'LOC004',
    type: 'LOCATION',
    name: 'Highland Transit Point',
    aliases: ['Checkpost 7', 'Valley Crossing'],
    status: 'ACTIVE',
    basePriority: 58,
    role: 'Highway Checkpoint & Staging Stop',
    createdAt: '2026-05-18',
    description: 'Synthetic mountain-pass weigh station and overnight vehicle rest area.',
    coordinates: '29.9457° N, 78.1642° E',
    zone: 'Hill State Highway'
  },
  {
    id: 'LOC005',
    type: 'LOCATION',
    name: 'Metro Plaza Office Complex',
    aliases: ['Tower B Suites'],
    status: 'ACTIVE',
    basePriority: 66,
    role: 'Corporate Management Suites',
    createdAt: '2026-05-01',
    description: 'Synthetic commercial high-rise housing trading and investment offices.',
    coordinates: '28.4595° N, 77.0266° E',
    zone: 'Commercial Business District'
  },
  {
    id: 'LOC006',
    type: 'LOCATION',
    name: 'Industrial Bypass Depot',
    aliases: ['Depot 9B', 'Auxiliary Yard'],
    status: 'ACTIVE',
    basePriority: 60,
    role: 'Auxiliary Haulage Yard',
    createdAt: '2026-05-25',
    description: 'Synthetic maintenance garage and trailer staging facility.',
    coordinates: '28.3880° N, 77.3150° E',
    zone: 'Southern Outer Ring'
  },

  // --- 5 SYNTHETIC FIR / CASE NODES ---
  {
    id: 'CASE001',
    type: 'CASE',
    name: 'FIR-2026-081: Freight Diversion',
    aliases: ['Case 81/26', 'Operation Waybill'],
    status: 'ACTIVE',
    basePriority: 86,
    role: 'Active Formal Investigation',
    createdAt: '2026-07-22',
    description: 'Synthetic investigation into unauthorized rerouting of heavy freight containers.',
    caseNumber: 'FIR-2026-081',
    station: 'Central Industrial Division',
    offence: 'Breach of Transit Manifest & Cargo Diversion',
    filingDate: '2026-07-22'
  },
  {
    id: 'CASE002',
    type: 'CASE',
    name: 'FIR-2026-104: Telecommunication Relay',
    aliases: ['Case 104/26', 'Signal Audit'],
    status: 'ACTIVE',
    basePriority: 82,
    role: 'Active Regulatory Case',
    createdAt: '2026-08-05',
    description: 'Synthetic probe into unauthorized cellular multiplexers and clone SIM operations.',
    caseNumber: 'FIR-2026-104',
    station: 'Cyber & Telecom Inquiry Cell',
    offence: 'Unauthorized Telecom Gateway Intercept',
    filingDate: '2026-08-05'
  },
  {
    id: 'CASE003',
    type: 'CASE',
    name: 'FIR-2026-139: Settlement Accounts',
    aliases: ['Case 139/26', 'Escrow Review'],
    status: 'UNDER_REVIEW',
    basePriority: 74,
    role: 'Financial Review Case',
    createdAt: '2026-08-14',
    description: 'Synthetic inquiry into high-value unbacked ledger credits and escrow transfers.',
    caseNumber: 'FIR-2026-139',
    station: 'Economic Offence Wing',
    offence: 'Unlawful Escrow Routing & Forged Credits',
    filingDate: '2026-08-14'
  },
  {
    id: 'CASE004',
    type: 'CASE',
    name: 'FIR-2025-412: Cargo Tampering',
    aliases: ['Old File 412'],
    status: 'CLOSED',
    basePriority: 40,
    role: 'Archived Reference Dossier',
    createdAt: '2025-11-19',
    description: 'Synthetic archived case regarding seal tampering on regional flatbed trucks.',
    caseNumber: 'FIR-2025-412',
    station: 'District Transit Post',
    offence: 'Transit Seal Compromise',
    filingDate: '2025-11-19'
  },
  {
    id: 'CASE005',
    type: 'CASE',
    name: 'FIR-2026-205: Transit Permits',
    aliases: ['Case 205/26', 'Permit Audit'],
    status: 'ACTIVE',
    basePriority: 78,
    role: 'Active Compliance Case',
    createdAt: '2026-08-27',
    description: 'Synthetic inquiry into duplicate highway transit passes and digital barcodes.',
    caseNumber: 'FIR-2026-205',
    station: 'Highway Vigilance Wing',
    offence: 'Counterfeit Digital Manifests',
    filingDate: '2026-08-27'
  },

  // --- 8 SYNTHETIC EVENTS ---
  {
    id: 'EVT001',
    type: 'EVENT',
    name: 'Night Transport Convoy',
    aliases: ['Convoy Alpha'],
    status: 'ACTIVE',
    basePriority: 80,
    role: 'Scheduled Freight Movement',
    createdAt: '2026-08-11',
    date: '2026-08-11',
    time: '23:30',
    description: 'Synthetic coordinated haulage of 4 heavy container vehicles through highway corridor.',
    locationId: 'LOC001'
  },
  {
    id: 'EVT002',
    type: 'EVENT',
    name: 'Terminal Staging Meeting',
    aliases: ['Yard Staging Briefing'],
    status: 'ACTIVE',
    basePriority: 75,
    role: 'Physical Operative Assembly',
    createdAt: '2026-08-14',
    date: '2026-08-14',
    time: '14:15',
    description: 'Synthetic rendezvous of fleet supervisors and dispatchers at central terminal.',
    locationId: 'LOC002'
  },
  {
    id: 'EVT003',
    type: 'EVENT',
    name: 'Financial Settlement Session',
    aliases: ['Audit Review 3'],
    status: 'ACTIVE',
    basePriority: 70,
    role: 'Commercial Settlement Review',
    createdAt: '2026-08-18',
    date: '2026-08-18',
    time: '16:45',
    description: 'Synthetic escrow accounts reconciliation and disbursement check at corporate plaza.',
    locationId: 'LOC005'
  },
  {
    id: 'EVT004',
    type: 'EVENT',
    name: 'Cargo Transfer at Industrial Depot',
    aliases: ['Offload Ops'],
    status: 'ACTIVE',
    basePriority: 82,
    role: 'Container Cross-Dock Operation',
    createdAt: '2026-08-22',
    date: '2026-08-22',
    time: '03:10',
    description: 'Synthetic late-night container transfer between prime hauler and auxiliary vans.',
    locationId: 'LOC006'
  },
  {
    id: 'EVT005',
    type: 'EVENT',
    name: 'Comms Spike Window',
    aliases: ['Relay Surge Alpha'],
    status: 'ACTIVE',
    basePriority: 88,
    role: 'Telecommunication Surge Window',
    createdAt: '2026-08-25',
    date: '2026-08-25',
    time: '20:00',
    description: 'Synthetic surge of rapid back-to-back phone contacts across 4 handsets within 90 minutes.',
    locationId: 'LOC002'
  },
  {
    id: 'EVT006',
    type: 'EVENT',
    name: 'Inter-State Vehicle Movement',
    aliases: ['Transit Run Bravo'],
    status: 'ACTIVE',
    basePriority: 66,
    role: 'High-Altitude Corridor Run',
    createdAt: '2026-08-28',
    date: '2026-08-28',
    time: '06:30',
    description: 'Synthetic convoy pass observed through Highland transit checkpoint.',
    locationId: 'LOC004'
  },
  {
    id: 'EVT007',
    type: 'EVENT',
    name: 'Port Clearance Inspection',
    aliases: ['Bonded Dock Clearance'],
    status: 'UNDER_REVIEW',
    basePriority: 62,
    role: 'Regulatory Customs Audit',
    createdAt: '2026-09-02',
    date: '2026-09-02',
    time: '11:00',
    description: 'Synthetic inspection of warehouse seals and container tare weight.',
    locationId: 'LOC003'
  },
  {
    id: 'EVT008',
    type: 'EVENT',
    name: 'Executive Strategy Briefing',
    aliases: ['Q3 Governance Call'],
    status: 'ACTIVE',
    basePriority: 73,
    role: 'Executive Management Assembly',
    createdAt: '2026-09-06',
    date: '2026-09-06',
    time: '17:30',
    description: 'Synthetic high-level conference between syndicate directors and trading coordinators.',
    locationId: 'LOC005'
  },

  // --- 5 SYNTHETIC VEHICLES ---
  {
    id: 'VEH001',
    type: 'VEHICLE',
    name: 'Heavy Hauler UK07-TR-9182',
    aliases: ['Rig 9182', 'Prime Hauler'],
    status: 'ACTIVE',
    basePriority: 81,
    role: '40-Foot Multi-Axle Container Hauler',
    createdAt: '2026-06-08',
    description: 'Synthetic commercial heavy cargo rig registered to Northstar fleet.',
    vehicleType: 'Heavy Multi-Axle Hauler',
    registration: 'UK-07-TR-9182'
  },
  {
    id: 'VEH002',
    type: 'VEHICLE',
    name: 'Transit Van DL05-VT-4410',
    aliases: ['Panel Van 4410'],
    status: 'ACTIVE',
    basePriority: 74,
    role: 'Medium Cargo Courier Van',
    createdAt: '2026-06-14',
    description: 'Synthetic logistics transport van observed at intermodal yards.',
    vehicleType: 'Medium Transit Van',
    registration: 'DL-05-VT-4410'
  },
  {
    id: 'VEH003',
    type: 'VEHICLE',
    name: 'Fleet Pickup UP14-FL-3309',
    aliases: ['Utility 3309', 'Broker Runabout'],
    status: 'ACTIVE',
    basePriority: 77,
    role: 'High-Mobility Utility Pickup',
    createdAt: '2026-06-18',
    description: 'Synthetic utility truck registered to trade broker liaison.',
    vehicleType: 'Utility Pickup',
    registration: 'UP-14-FL-3309'
  },
  {
    id: 'VEH004',
    type: 'VEHICLE',
    name: 'Container Truck MH04-CT-8812',
    aliases: ['Intermodal Rig 8812'],
    status: 'ACTIVE',
    basePriority: 69,
    role: 'Port Container Carrier',
    createdAt: '2026-06-21',
    description: 'Synthetic commercial trailer operating between port park and terminal.',
    vehicleType: 'Commercial Container Rig',
    registration: 'MH-04-CT-8812'
  },
  {
    id: 'VEH005',
    type: 'VEHICLE',
    name: 'Utility SUV HR26-SU-5501',
    aliases: ['Supervision SUV 5501'],
    status: 'ACTIVE',
    basePriority: 63,
    role: 'Executive Field Escort SUV',
    createdAt: '2026-06-30',
    description: 'Synthetic passenger SUV utilized by corporate directors and inspectors.',
    vehicleType: 'Executive SUV',
    registration: 'HR-26-SU-5501'
  },

  // --- 3 SYNTHETIC ORGANIZATIONS ---
  {
    id: 'ORG001',
    type: 'ORGANIZATION',
    name: 'Northstar Logistics Syndicate',
    aliases: ['Northstar Transport Group'],
    status: 'ACTIVE',
    basePriority: 87,
    role: 'Regional Freight Transport Consortium',
    createdAt: '2026-04-10',
    description: 'Synthetic commercial umbrella syndicate coordinating container logistics across state borders.',
    sector: 'Multi-Modal Logistics',
    headquarters: 'North Sector Warehouse Hub'
  },
  {
    id: 'ORG002',
    type: 'ORGANIZATION',
    name: 'Blue Ridge Traders Ltd',
    aliases: ['Blue Ridge Commodities'],
    status: 'ACTIVE',
    basePriority: 83,
    role: 'Inter-State Wholesale Trading Firm',
    createdAt: '2026-04-18',
    description: 'Synthetic wholesale import-export entity financing cargo consignments.',
    sector: 'Wholesale Trade & Distribution',
    headquarters: 'Metro Plaza Office Complex'
  },
  {
    id: 'ORG003',
    type: 'ORGANIZATION',
    name: 'Apex Commercial Services',
    aliases: ['Apex Escrow Solutions'],
    status: 'ACTIVE',
    basePriority: 75,
    role: 'Settlement & Logistics Advisory',
    createdAt: '2026-04-25',
    description: 'Synthetic intermediary provider handling freight factoring and escrow clearance.',
    sector: 'Commercial Advisory & Clearance',
    headquarters: 'Metro Plaza Office Complex'
  }
]

// ====================================================
// 2. RELATIONSHIPS (ALL EDGES DERIVED FROM DATA.JS)
// Strict rule: No edges hard-coded in React components
// ====================================================

export const relationships = [
  // --- CLUSTER A: NORTHSTAR LOGISTICS (COMMUNICATIONS & FLEET) ---
  {
    id: 'R001',
    source: 'P001',
    target: 'P002',
    type: 'ASSOCIATED_WITH',
    category: 'ASSOCIATION',
    confidence: 0.94,
    date: '2026-08-11',
    evidenceIds: ['EV001', 'EV007'],
    description: 'Synthetic demonstration coordination observed between fleet coordinator and primary contractor.',
    evidenceSupport: 38,
    commSupport: 24,
    tempConsistency: 19,
    sourceRel: 13
  },
  {
    id: 'R002',
    source: 'P001',
    target: 'PH001',
    type: 'USED_PHONE',
    category: 'COMMUNICATION',
    confidence: 0.96,
    date: '2026-08-01',
    evidenceIds: ['EV001', 'EV002'],
    description: 'Synthetic device subscriber registration and subscriber activity records.',
    evidenceSupport: 39,
    commSupport: 25,
    tempConsistency: 18,
    sourceRel: 14
  },
  {
    id: 'R003',
    source: 'P002',
    target: 'PH002',
    type: 'USED_PHONE',
    category: 'COMMUNICATION',
    confidence: 0.95,
    date: '2026-08-01',
    evidenceIds: ['EV002', 'EV003'],
    description: 'Synthetic SIM issuance and continuous tower telemetry link.',
    evidenceSupport: 38,
    commSupport: 24,
    tempConsistency: 19,
    sourceRel: 14
  },
  {
    id: 'R004',
    source: 'P001',
    target: 'P004',
    type: 'KNOWS',
    category: 'ASSOCIATION',
    confidence: 0.88,
    date: '2026-08-10',
    evidenceIds: ['EV004'],
    description: 'Synthetic direct operational instructions for terminal staging docks.',
    evidenceSupport: 35,
    commSupport: 22,
    tempConsistency: 17,
    sourceRel: 14
  },
  {
    id: 'R005',
    source: 'P002',
    target: 'P004',
    type: 'ASSOCIATED_WITH',
    category: 'ASSOCIATION',
    confidence: 0.89,
    date: '2026-08-12',
    evidenceIds: ['EV005'],
    description: 'Synthetic daily dispatch logs linking contractor orders to warehouse loading bays.',
    evidenceSupport: 36,
    commSupport: 21,
    tempConsistency: 18,
    sourceRel: 14
  },
  {
    id: 'R006',
    source: 'P001',
    target: 'ORG001',
    type: 'WORKS_FOR',
    category: 'MEMBERSHIP',
    confidence: 0.95,
    date: '2026-06-12',
    evidenceIds: ['EV006'],
    description: 'Synthetic employment registry listing P001 as senior fleet coordinator.',
    evidenceSupport: 39,
    commSupport: 23,
    tempConsistency: 19,
    sourceRel: 14
  },
  {
    id: 'R007',
    source: 'P002',
    target: 'ORG001',
    type: 'LEADS',
    category: 'MEMBERSHIP',
    confidence: 0.92,
    date: '2026-06-15',
    evidenceIds: ['EV006', 'EV007'],
    description: 'Synthetic commercial charter authorizing contractor authority over dispatch.',
    evidenceSupport: 37,
    commSupport: 23,
    tempConsistency: 18,
    sourceRel: 14
  },
  {
    id: 'R008',
    source: 'P004',
    target: 'ORG001',
    type: 'MEMBER_OF',
    category: 'MEMBERSHIP',
    confidence: 0.91,
    date: '2026-06-18',
    evidenceIds: ['EV006'],
    description: 'Synthetic facility roster placing P004 under Northstar operations division.',
    evidenceSupport: 36,
    commSupport: 23,
    tempConsistency: 18,
    sourceRel: 14
  },
  {
    id: 'R009',
    source: 'P006',
    target: 'ORG001',
    type: 'WORKS_FOR',
    category: 'MEMBERSHIP',
    confidence: 0.86,
    date: '2026-07-01',
    evidenceIds: ['EV006'],
    description: 'Synthetic driver team roster under Northstar logistics night operations.',
    evidenceSupport: 34,
    commSupport: 22,
    tempConsistency: 17,
    sourceRel: 13
  },
  {
    id: 'R010',
    source: 'P006',
    target: 'P002',
    type: 'REPORTS_TO',
    category: 'ASSOCIATION',
    confidence: 0.90,
    date: '2026-08-08',
    evidenceIds: ['EV008'],
    description: 'Synthetic operational hierarchy: driver team lead reports to fleet contractor.',
    evidenceSupport: 36,
    commSupport: 23,
    tempConsistency: 18,
    sourceRel: 13
  },
  {
    id: 'R011',
    source: 'P006',
    target: 'PH006',
    type: 'USED_PHONE',
    category: 'COMMUNICATION',
    confidence: 0.89,
    date: '2026-07-02',
    evidenceIds: ['EV009'],
    description: 'Synthetic vehicle satellite unit logged to driver identity during night runs.',
    evidenceSupport: 36,
    commSupport: 22,
    tempConsistency: 18,
    sourceRel: 13
  },
  {
    id: 'R012',
    source: 'P002',
    target: 'VEH001',
    type: 'OWNS',
    category: 'VEHICLE',
    confidence: 0.94,
    date: '2026-06-08',
    evidenceIds: ['EV010'],
    description: 'Synthetic commercial lease agreement registering heavy hauler to contractor.',
    evidenceSupport: 38,
    commSupport: 24,
    tempConsistency: 18,
    sourceRel: 14
  },
  {
    id: 'R013',
    source: 'P001',
    target: 'VEH002',
    type: 'USED_VEHICLE',
    category: 'VEHICLE',
    confidence: 0.87,
    date: '2026-08-11',
    evidenceIds: ['EV011'],
    description: 'Synthetic terminal gate log verifying P001 authorization of Transit Van DL05-VT-4410.',
    evidenceSupport: 35,
    commSupport: 21,
    tempConsistency: 18,
    sourceRel: 13
  },
  {
    id: 'R014',
    source: 'P006',
    target: 'VEH001',
    type: 'USED_VEHICLE',
    category: 'VEHICLE',
    confidence: 0.91,
    date: '2026-08-11',
    evidenceIds: ['EV008', 'EV010'],
    description: 'Synthetic vehicle trip card showing P006 piloted heavy rig UK07-TR-9182.',
    evidenceSupport: 37,
    commSupport: 22,
    tempConsistency: 18,
    sourceRel: 14
  },
  {
    id: 'R015',
    source: 'P001',
    target: 'LOC001',
    type: 'VISITED',
    category: 'LOCATION',
    confidence: 0.93,
    date: '2026-08-11',
    evidenceIds: ['EV012'],
    description: 'Synthetic biometric badge records at North Sector Warehouse Hub.',
    evidenceSupport: 38,
    commSupport: 23,
    tempConsistency: 18,
    sourceRel: 14
  },
  {
    id: 'R016',
    source: 'P002',
    target: 'LOC001',
    type: 'VISITED',
    category: 'LOCATION',
    confidence: 0.92,
    date: '2026-08-11',
    evidenceIds: ['EV012'],
    description: 'Synthetic physical badge swipe timestamp matching P001 at North Sector Hub.',
    evidenceSupport: 37,
    commSupport: 23,
    tempConsistency: 18,
    sourceRel: 14
  },
  {
    id: 'R017',
    source: 'P004',
    target: 'LOC002',
    type: 'LOCATED_AT',
    category: 'LOCATION',
    confidence: 0.95,
    date: '2026-08-14',
    evidenceIds: ['EV013'],
    description: 'Synthetic permanent duty post stationed at Central Freight Terminal.',
    evidenceSupport: 39,
    commSupport: 23,
    tempConsistency: 19,
    sourceRel: 14
  },
  {
    id: 'R018',
    source: 'P001',
    target: 'LOC002',
    type: 'VISITED',
    category: 'LOCATION',
    confidence: 0.89,
    date: '2026-08-14',
    evidenceIds: ['EV013'],
    description: 'Synthetic visitor pass log for terminal staging conference.',
    evidenceSupport: 36,
    commSupport: 22,
    tempConsistency: 17,
    sourceRel: 14
  },
  {
    id: 'R019',
    source: 'P002',
    target: 'LOC002',
    type: 'VISITED',
    category: 'LOCATION',
    confidence: 0.90,
    date: '2026-08-14',
    evidenceIds: ['EV013'],
    description: 'Synthetic parking sensor and terminal entry gate confirmation.',
    evidenceSupport: 36,
    commSupport: 23,
    tempConsistency: 17,
    sourceRel: 14
  },
  {
    id: 'R020',
    source: 'P001',
    target: 'CASE001',
    type: 'INVOLVED_IN',
    category: 'CASE',
    confidence: 0.93,
    date: '2026-07-22',
    evidenceIds: ['EV014'],
    description: 'Synthetic FIR named subject listed as freight dispatch signatory in manifest audit.',
    evidenceSupport: 38,
    commSupport: 23,
    tempConsistency: 18,
    sourceRel: 14
  },
  {
    id: 'R021',
    source: 'P002',
    target: 'CASE001',
    type: 'INVOLVED_IN',
    category: 'CASE',
    confidence: 0.92,
    date: '2026-07-22',
    evidenceIds: ['EV014'],
    description: 'Synthetic contractor inquiry regarding container rerouting orders.',
    evidenceSupport: 37,
    commSupport: 23,
    tempConsistency: 18,
    sourceRel: 14
  },
  {
    id: 'R022',
    source: 'P004',
    target: 'CASE001',
    type: 'MENTIONED_IN',
    category: 'CASE',
    confidence: 0.84,
    date: '2026-07-25',
    evidenceIds: ['EV014'],
    description: 'Synthetic witness statement referencing terminal supervisor sign-off on gate passes.',
    evidenceSupport: 33,
    commSupport: 21,
    tempConsistency: 17,
    sourceRel: 13
  },
  {
    id: 'R023',
    source: 'P001',
    target: 'EVT001',
    type: 'ATTENDED',
    category: 'EVENT',
    confidence: 0.91,
    date: '2026-08-11',
    evidenceIds: ['EV008'],
    description: 'Synthetic radio telemetry logged P001 during Night Transport Convoy.',
    evidenceSupport: 37,
    commSupport: 22,
    tempConsistency: 18,
    sourceRel: 14
  },
  {
    id: 'R024',
    source: 'P002',
    target: 'EVT001',
    type: 'INVOLVED_IN',
    category: 'EVENT',
    confidence: 0.93,
    date: '2026-08-11',
    evidenceIds: ['EV008'],
    description: 'Synthetic dispatch order issued under contractor credentials for Convoy Alpha.',
    evidenceSupport: 38,
    commSupport: 23,
    tempConsistency: 18,
    sourceRel: 14
  },
  {
    id: 'R025',
    source: 'P006',
    target: 'EVT001',
    type: 'ATTENDED',
    category: 'EVENT',
    confidence: 0.94,
    date: '2026-08-11',
    evidenceIds: ['EV008', 'EV010'],
    description: 'Synthetic vehicle trip GPS placing P006 in convoy lead vehicle.',
    evidenceSupport: 38,
    commSupport: 24,
    tempConsistency: 18,
    sourceRel: 14
  },
  {
    id: 'R026',
    source: 'P001',
    target: 'EVT002',
    type: 'ATTENDED',
    category: 'EVENT',
    confidence: 0.89,
    date: '2026-08-14',
    evidenceIds: ['EV013'],
    description: 'Synthetic roster confirming attendance at Terminal Staging Meeting.',
    evidenceSupport: 36,
    commSupport: 22,
    tempConsistency: 17,
    sourceRel: 14
  },
  {
    id: 'R027',
    source: 'P002',
    target: 'EVT002',
    type: 'ATTENDED',
    category: 'EVENT',
    confidence: 0.90,
    date: '2026-08-14',
    evidenceIds: ['EV013'],
    description: 'Synthetic roster confirming contractor attendance at Yard Staging meeting.',
    evidenceSupport: 36,
    commSupport: 23,
    tempConsistency: 17,
    sourceRel: 14
  },
  {
    id: 'R028',
    source: 'P004',
    target: 'EVT002',
    type: 'ATTENDED',
    category: 'EVENT',
    confidence: 0.92,
    date: '2026-08-14',
    evidenceIds: ['EV013'],
    description: 'Synthetic host and coordinator for terminal staging session.',
    evidenceSupport: 37,
    commSupport: 23,
    tempConsistency: 18,
    sourceRel: 14
  },
  {
    id: 'R029',
    source: 'P007',
    target: 'P004',
    type: 'ASSOCIATED_WITH',
    category: 'ASSOCIATION',
    confidence: 0.81,
    date: '2026-08-15',
    evidenceIds: ['EV015'],
    description: 'Synthetic transit permit liaison coordinating manifest stamps with supervisor.',
    evidenceSupport: 32,
    commSupport: 20,
    tempConsistency: 16,
    sourceRel: 13
  },
  {
    id: 'R030',
    source: 'P007',
    target: 'LOC004',
    type: 'VISITED',
    category: 'LOCATION',
    confidence: 0.83,
    date: '2026-08-28',
    evidenceIds: ['EV016'],
    description: 'Synthetic toll checkpost pass logged to P007 at Highland Transit Point.',
    evidenceSupport: 33,
    commSupport: 21,
    tempConsistency: 16,
    sourceRel: 13
  },
  {
    id: 'R031',
    source: 'P007',
    target: 'CASE005',
    type: 'INVOLVED_IN',
    category: 'CASE',
    confidence: 0.85,
    date: '2026-08-27',
    evidenceIds: ['EV017'],
    description: 'Synthetic inquiry file naming transit liaison in duplicate barcode issuance.',
    evidenceSupport: 34,
    commSupport: 21,
    tempConsistency: 17,
    sourceRel: 13
  },

  // --- THE BRIDGE: P003 SAMEER KHAN (CROSS-CLUSTER CONNECTIONS) ---
  {
    id: 'R032',
    source: 'P003',
    target: 'P001',
    type: 'CONTACTED',
    category: 'COMMUNICATION',
    confidence: 0.93,
    date: '2026-08-16',
    evidenceIds: ['EV018', 'EV022'],
    description: 'Synthetic high-volume call records linking broker directly to fleet coordinator.',
    evidenceSupport: 38,
    commSupport: 24,
    tempConsistency: 18,
    sourceRel: 13
  },
  {
    id: 'R033',
    source: 'P003',
    target: 'P002',
    type: 'ASSOCIATED_WITH',
    category: 'ASSOCIATION',
    confidence: 0.95,
    date: '2026-08-16',
    evidenceIds: ['EV018', 'EV019'],
    description: 'Synthetic inter-state brokerage contract connecting transport contractor with trade consignments.',
    evidenceSupport: 39,
    commSupport: 24,
    tempConsistency: 18,
    sourceRel: 14
  },
  {
    id: 'R034',
    source: 'P003',
    target: 'PH003',
    type: 'USED_PHONE',
    category: 'COMMUNICATION',
    confidence: 0.96,
    date: '2026-06-15',
    evidenceIds: ['EV020'],
    description: 'Synthetic primary subscriber identity for high-volume relay handset.',
    evidenceSupport: 39,
    commSupport: 25,
    tempConsistency: 18,
    sourceRel: 14
  },
  {
    id: 'R035',
    source: 'P003',
    target: 'VEH003',
    type: 'OWNS',
    category: 'VEHICLE',
    confidence: 0.92,
    date: '2026-06-18',
    evidenceIds: ['EV021'],
    description: 'Synthetic vehicle registration card for Utility Pickup UP14-FL-3309.',
    evidenceSupport: 37,
    commSupport: 23,
    tempConsistency: 18,
    sourceRel: 14
  },
  {
    id: 'R036',
    source: 'P003',
    target: 'LOC002',
    type: 'VISITED',
    category: 'LOCATION',
    confidence: 0.91,
    date: '2026-08-14',
    evidenceIds: ['EV013'],
    description: 'Synthetic visitor checkpost entry confirming P003 presence during staging meeting.',
    evidenceSupport: 37,
    commSupport: 23,
    tempConsistency: 17,
    sourceRel: 14
  },
  {
    id: 'R037',
    source: 'P003',
    target: 'LOC005',
    type: 'VISITED',
    category: 'LOCATION',
    confidence: 0.90,
    date: '2026-08-18',
    evidenceIds: ['EV023'],
    description: 'Synthetic access badge swipe at Metro Plaza corporate suites.',
    evidenceSupport: 36,
    commSupport: 23,
    tempConsistency: 18,
    sourceRel: 13
  },
  {
    id: 'R038',
    source: 'P003',
    target: 'EVT002',
    type: 'ATTENDED',
    category: 'EVENT',
    confidence: 0.91,
    date: '2026-08-14',
    evidenceIds: ['EV013'],
    description: 'Synthetic meeting record linking P003 to Terminal Staging assembly.',
    evidenceSupport: 37,
    commSupport: 22,
    tempConsistency: 18,
    sourceRel: 14
  },
  {
    id: 'R039',
    source: 'P003',
    target: 'EVT005',
    type: 'INVOLVED_IN',
    category: 'EVENT',
    confidence: 0.94,
    date: '2026-08-25',
    evidenceIds: ['EV024'],
    description: 'Synthetic telemetry origin node for high-frequency telecommunication surge window.',
    evidenceSupport: 38,
    commSupport: 24,
    tempConsistency: 18,
    sourceRel: 14
  },
  {
    id: 'R040',
    source: 'P003',
    target: 'CASE002',
    type: 'INVOLVED_IN',
    category: 'CASE',
    confidence: 0.92,
    date: '2026-08-05',
    evidenceIds: ['EV025'],
    description: 'Synthetic FIR naming P003 device in unauthorized telecommunication relay probe.',
    evidenceSupport: 38,
    commSupport: 23,
    tempConsistency: 17,
    sourceRel: 14
  },

  // --- BRIDGE P003 CONNECTING INTO CLUSTER B (FINANCE & TRADING) ---
  {
    id: 'R041',
    source: 'P003',
    target: 'P005',
    type: 'ASSOCIATED_WITH',
    category: 'ASSOCIATION',
    confidence: 0.92,
    date: '2026-08-18',
    evidenceIds: ['EV023', 'EV026'],
    description: 'Synthetic joint transaction record between inter-city broker and settlement agent.',
    evidenceSupport: 37,
    commSupport: 23,
    tempConsistency: 18,
    sourceRel: 14
  },
  {
    id: 'R042',
    source: 'P003',
    target: 'ORG002',
    type: 'CONNECTED_TO',
    category: 'MEMBERSHIP',
    confidence: 0.89,
    date: '2026-06-25',
    evidenceIds: ['EV027'],
    description: 'Synthetic agency agreement retaining P003 as logistics procurement consultant.',
    evidenceSupport: 36,
    commSupport: 22,
    tempConsistency: 18,
    sourceRel: 13
  },

  // --- CLUSTER B: BLUE RIDGE TRADERS & APEX SERVICES (COMMERCIAL & FINANCE) ---
  {
    id: 'R043',
    source: 'P005',
    target: 'PH005',
    type: 'USED_PHONE',
    category: 'COMMUNICATION',
    confidence: 0.91,
    date: '2026-06-22',
    evidenceIds: ['EV028'],
    description: 'Synthetic encrypted device used for escrow transaction authorization.',
    evidenceSupport: 37,
    commSupport: 22,
    tempConsistency: 18,
    sourceRel: 14
  },
  {
    id: 'R044',
    source: 'P005',
    target: 'ORG002',
    type: 'WORKS_FOR',
    category: 'MEMBERSHIP',
    confidence: 0.94,
    date: '2026-06-25',
    evidenceIds: ['EV027'],
    description: 'Synthetic executive payroll file designating P005 as treasury manager.',
    evidenceSupport: 38,
    commSupport: 24,
    tempConsistency: 18,
    sourceRel: 14
  },
  {
    id: 'R045',
    source: 'P005',
    target: 'ORG003',
    type: 'MEMBER_OF',
    category: 'MEMBERSHIP',
    confidence: 0.88,
    date: '2026-07-01',
    evidenceIds: ['EV029'],
    description: 'Synthetic commercial advisory board membership in Apex Commercial Services.',
    evidenceSupport: 35,
    commSupport: 22,
    tempConsistency: 18,
    sourceRel: 13
  },
  {
    id: 'R046',
    source: 'P010',
    target: 'ORG002',
    type: 'LEADS',
    category: 'MEMBERSHIP',
    confidence: 0.96,
    date: '2026-06-01',
    evidenceIds: ['EV027'],
    description: 'Synthetic corporate charter appointing P010 as Managing Director of Blue Ridge.',
    evidenceSupport: 39,
    commSupport: 25,
    tempConsistency: 18,
    sourceRel: 14
  },
  {
    id: 'R047',
    source: 'P010',
    target: 'ORG003',
    type: 'MANAGES',
    category: 'MEMBERSHIP',
    confidence: 0.93,
    date: '2026-06-05',
    evidenceIds: ['EV029'],
    description: 'Synthetic controlling interest declaration filing for Apex Commercial Services.',
    evidenceSupport: 38,
    commSupport: 23,
    tempConsistency: 18,
    sourceRel: 14
  },
  {
    id: 'R048',
    source: 'P010',
    target: 'PH008',
    type: 'USED_PHONE',
    category: 'COMMUNICATION',
    confidence: 0.95,
    date: '2026-06-05',
    evidenceIds: ['EV030'],
    description: 'Synthetic executive voice channel registered to corporate headquarters.',
    evidenceSupport: 39,
    commSupport: 24,
    tempConsistency: 18,
    sourceRel: 14
  },
  {
    id: 'R049',
    source: 'P005',
    target: 'P010',
    type: 'REPORTS_TO',
    category: 'ASSOCIATION',
    confidence: 0.94,
    date: '2026-06-25',
    evidenceIds: ['EV027'],
    description: 'Synthetic organizational reporting line: settlement agent reports to director.',
    evidenceSupport: 38,
    commSupport: 24,
    tempConsistency: 18,
    sourceRel: 14
  },
  {
    id: 'R050',
    source: 'P009',
    target: 'P010',
    type: 'WORKS_FOR',
    category: 'ASSOCIATION',
    confidence: 0.87,
    date: '2026-07-14',
    evidenceIds: ['EV031'],
    description: 'Synthetic trade procurement contract executed under P010 supervision.',
    evidenceSupport: 35,
    commSupport: 21,
    tempConsistency: 18,
    sourceRel: 13
  },
  {
    id: 'R051',
    source: 'P009',
    target: 'ORG002',
    type: 'MEMBER_OF',
    category: 'MEMBERSHIP',
    confidence: 0.90,
    date: '2026-07-14',
    evidenceIds: ['EV027', 'EV031'],
    description: 'Synthetic trade representative credential issued by Blue Ridge Traders.',
    evidenceSupport: 36,
    commSupport: 23,
    tempConsistency: 18,
    sourceRel: 13
  },
  {
    id: 'R052',
    source: 'P008',
    target: 'ORG003',
    type: 'WORKS_FOR',
    category: 'MEMBERSHIP',
    confidence: 0.86,
    date: '2026-07-10',
    evidenceIds: ['EV029'],
    description: 'Synthetic technical maintenance contractor at Apex Commercial Services.',
    evidenceSupport: 34,
    commSupport: 22,
    tempConsistency: 17,
    sourceRel: 13
  },
  {
    id: 'R053',
    source: 'P008',
    target: 'P005',
    type: 'ASSOCIATED_WITH',
    category: 'ASSOCIATION',
    confidence: 0.85,
    date: '2026-08-01',
    evidenceIds: ['EV029', 'EV032'],
    description: 'Synthetic hardware telemetry logs provided by technician to accounts team.',
    evidenceSupport: 34,
    commSupport: 21,
    tempConsistency: 17,
    sourceRel: 13
  },
  {
    id: 'R054',
    source: 'P005',
    target: 'LOC005',
    type: 'LOCATED_AT',
    category: 'LOCATION',
    confidence: 0.94,
    date: '2026-08-18',
    evidenceIds: ['EV023'],
    description: 'Synthetic daily office badge logs at Metro Plaza Office Complex.',
    evidenceSupport: 38,
    commSupport: 24,
    tempConsistency: 18,
    sourceRel: 14
  },
  {
    id: 'R055',
    source: 'P010',
    target: 'LOC005',
    type: 'LOCATED_AT',
    category: 'LOCATION',
    confidence: 0.95,
    date: '2026-08-18',
    evidenceIds: ['EV023'],
    description: 'Synthetic executive suite occupancy record at Metro Plaza.',
    evidenceSupport: 39,
    commSupport: 24,
    tempConsistency: 18,
    sourceRel: 14
  },
  {
    id: 'R056',
    source: 'P009',
    target: 'LOC003',
    type: 'VISITED',
    category: 'LOCATION',
    confidence: 0.89,
    date: '2026-09-02',
    evidenceIds: ['EV031'],
    description: 'Synthetic customs gate entry record at Portview Logistics Park.',
    evidenceSupport: 36,
    commSupport: 22,
    tempConsistency: 18,
    sourceRel: 13
  },
  {
    id: 'R057',
    source: 'P010',
    target: 'VEH005',
    type: 'OWNS',
    category: 'VEHICLE',
    confidence: 0.92,
    date: '2026-06-30',
    evidenceIds: ['EV030'],
    description: 'Synthetic corporate transport assignment of Utility SUV HR26-SU-5501.',
    evidenceSupport: 37,
    commSupport: 23,
    tempConsistency: 18,
    sourceRel: 14
  },
  {
    id: 'R058',
    source: 'P005',
    target: 'CASE003',
    type: 'INVOLVED_IN',
    category: 'CASE',
    confidence: 0.88,
    date: '2026-08-14',
    evidenceIds: ['EV026'],
    description: 'Synthetic escrow inquiry record linking P005 to unbacked credits investigation.',
    evidenceSupport: 35,
    commSupport: 22,
    tempConsistency: 18,
    sourceRel: 13
  },
  {
    id: 'R059',
    source: 'P010',
    target: 'CASE003',
    type: 'MENTIONED_IN',
    category: 'CASE',
    confidence: 0.85,
    date: '2026-08-14',
    evidenceIds: ['EV026'],
    description: 'Synthetic reference to director signature in corporate account audit.',
    evidenceSupport: 34,
    commSupport: 21,
    tempConsistency: 17,
    sourceRel: 13
  },
  {
    id: 'R060',
    source: 'P005',
    target: 'EVT003',
    type: 'ATTENDED',
    category: 'EVENT',
    confidence: 0.93,
    date: '2026-08-18',
    evidenceIds: ['EV023'],
    description: 'Synthetic attendee log at Financial Settlement Session in Metro Plaza.',
    evidenceSupport: 38,
    commSupport: 23,
    tempConsistency: 18,
    sourceRel: 14
  },
  {
    id: 'R061',
    source: 'P010',
    target: 'EVT008',
    type: 'ATTENDED',
    category: 'EVENT',
    confidence: 0.94,
    date: '2026-09-06',
    evidenceIds: ['EV030'],
    description: 'Synthetic chair for Executive Strategy Briefing.',
    evidenceSupport: 38,
    commSupport: 24,
    tempConsistency: 18,
    sourceRel: 14
  },
  {
    id: 'R062',
    source: 'P009',
    target: 'EVT007',
    type: 'ATTENDED',
    category: 'EVENT',
    confidence: 0.88,
    date: '2026-09-02',
    evidenceIds: ['EV031'],
    description: 'Synthetic presence at Port Clearance Inspection.',
    evidenceSupport: 35,
    commSupport: 22,
    tempConsistency: 18,
    sourceRel: 13
  },
  {
    id: 'R063',
    source: 'VEH004',
    target: 'LOC003',
    type: 'LOCATED_AT',
    category: 'LOCATION',
    confidence: 0.91,
    date: '2026-09-02',
    evidenceIds: ['EV031'],
    description: 'Synthetic weighbridge scan of Container Truck MH04-CT-8812 at Portview.',
    evidenceSupport: 37,
    commSupport: 22,
    tempConsistency: 18,
    sourceRel: 14
  },
  {
    id: 'R064',
    source: 'ORG001',
    target: 'ORG002',
    type: 'CONNECTED_TO',
    category: 'ASSOCIATION',
    confidence: 0.90,
    date: '2026-07-15',
    evidenceIds: ['EV027'],
    description: 'Synthetic master transport service contract between Northstar and Blue Ridge.',
    evidenceSupport: 36,
    commSupport: 23,
    tempConsistency: 18,
    sourceRel: 13
  }
]

// ==========================================
// 3. SYNTHETIC CDR RECORDS (30–50 CALLS)
// Realistic timestamps across August-Sept 2026
// ==========================================

export const cdrRecords = [
  {
    id: 'CDR001',
    caller: 'P001',
    receiver: 'P002',
    callerPhone: 'PH001',
    receiverPhone: 'PH002',
    timestamp: '2026-08-11T21:14:00',
    durationSeconds: 420,
    callType: 'VOICE',
    location: 'LOC001',
    tower: 'North Industrial Cell A-12',
    source: 'Synthetic CDR Stream'
  },
  {
    id: 'CDR002',
    caller: 'P002',
    receiver: 'P001',
    callerPhone: 'PH002',
    receiverPhone: 'PH001',
    timestamp: '2026-08-11T21:38:00',
    durationSeconds: 310,
    callType: 'VOICE',
    location: 'LOC001',
    tower: 'North Industrial Cell A-12',
    source: 'Synthetic CDR Stream'
  },
  {
    id: 'CDR003',
    caller: 'P001',
    receiver: 'P004',
    callerPhone: 'PH001',
    receiverPhone: 'PH004',
    timestamp: '2026-08-12T09:15:00',
    durationSeconds: 185,
    callType: 'VOICE',
    location: 'LOC001',
    tower: 'North Industrial Cell B-04',
    source: 'Synthetic CDR Stream'
  },
  {
    id: 'CDR004',
    caller: 'P002',
    receiver: 'P004',
    callerPhone: 'PH002',
    receiverPhone: 'PH004',
    timestamp: '2026-08-12T14:22:00',
    durationSeconds: 540,
    callType: 'VOICE',
    location: 'LOC002',
    tower: 'Central Terminal Sector 3',
    source: 'Synthetic CDR Stream'
  },
  {
    id: 'CDR005',
    caller: 'P002',
    receiver: 'P006',
    callerPhone: 'PH002',
    receiverPhone: 'PH006',
    timestamp: '2026-08-12T18:40:00',
    durationSeconds: 260,
    callType: 'VOICE',
    location: 'LOC002',
    tower: 'Central Terminal Sector 3',
    source: 'Synthetic CDR Stream'
  },
  {
    id: 'CDR006',
    caller: 'P006',
    receiver: 'P001',
    callerPhone: 'PH006',
    receiverPhone: 'PH001',
    timestamp: '2026-08-13T08:12:00',
    durationSeconds: 145,
    callType: 'VOICE',
    location: 'LOC001',
    tower: 'North Industrial Cell A-12',
    source: 'Synthetic CDR Stream'
  },
  {
    id: 'CDR007',
    caller: 'P001',
    receiver: 'P002',
    callerPhone: 'PH001',
    receiverPhone: 'PH002',
    timestamp: '2026-08-13T22:05:00',
    durationSeconds: 615,
    callType: 'VOICE',
    location: 'LOC001',
    tower: 'North Industrial Cell A-12',
    source: 'Synthetic CDR Stream'
  },
  {
    id: 'CDR008',
    caller: 'P003',
    receiver: 'P001',
    callerPhone: 'PH003',
    receiverPhone: 'PH001',
    timestamp: '2026-08-14T11:30:00',
    durationSeconds: 480,
    callType: 'VOICE',
    location: 'LOC002',
    tower: 'Central Terminal Sector 1',
    source: 'Synthetic CDR Stream'
  },
  {
    id: 'CDR009',
    caller: 'P002',
    receiver: 'P003',
    callerPhone: 'PH002',
    receiverPhone: 'PH003',
    timestamp: '2026-08-14T12:05:00',
    durationSeconds: 720,
    callType: 'VOICE',
    location: 'LOC002',
    tower: 'Central Terminal Sector 1',
    source: 'Synthetic CDR Stream'
  },
  {
    id: 'CDR010',
    caller: 'P003',
    receiver: 'P005',
    callerPhone: 'PH003',
    receiverPhone: 'PH005',
    timestamp: '2026-08-14T15:45:00',
    durationSeconds: 390,
    callType: 'VOICE',
    location: 'LOC005',
    tower: 'Metro CBD Tower South',
    source: 'Synthetic CDR Stream'
  },
  {
    id: 'CDR011',
    caller: 'P005',
    receiver: 'P010',
    callerPhone: 'PH005',
    receiverPhone: 'PH008',
    timestamp: '2026-08-14T16:20:00',
    durationSeconds: 310,
    callType: 'VOICE',
    location: 'LOC005',
    tower: 'Metro CBD Tower North',
    source: 'Synthetic CDR Stream'
  },
  {
    id: 'CDR012',
    caller: 'P001',
    receiver: 'P002',
    callerPhone: 'PH001',
    receiverPhone: 'PH002',
    timestamp: '2026-08-15T20:10:00',
    durationSeconds: 340,
    callType: 'VOICE',
    location: 'LOC001',
    tower: 'North Industrial Cell A-12',
    source: 'Synthetic CDR Stream'
  },
  {
    id: 'CDR013',
    caller: 'P004',
    receiver: 'P007',
    callerPhone: 'PH004',
    receiverPhone: 'PH007',
    timestamp: '2026-08-15T21:40:00',
    durationSeconds: 210,
    callType: 'VOICE',
    location: 'LOC002',
    tower: 'Central Terminal Sector 3',
    source: 'Synthetic CDR Stream'
  },
  {
    id: 'CDR014',
    caller: 'P003',
    receiver: 'P002',
    callerPhone: 'PH003',
    receiverPhone: 'PH002',
    timestamp: '2026-08-16T10:15:00',
    durationSeconds: 510,
    callType: 'VOICE',
    location: 'LOC002',
    tower: 'Central Terminal Sector 2',
    source: 'Synthetic CDR Stream'
  },
  {
    id: 'CDR015',
    caller: 'P001',
    receiver: 'P003',
    callerPhone: 'PH001',
    receiverPhone: 'PH003',
    timestamp: '2026-08-16T17:25:00',
    durationSeconds: 430,
    callType: 'VOICE',
    location: 'LOC001',
    tower: 'North Industrial Cell A-12',
    source: 'Synthetic CDR Stream'
  },
  {
    id: 'CDR016',
    caller: 'P003',
    receiver: 'P005',
    callerPhone: 'PH003',
    receiverPhone: 'PH005',
    timestamp: '2026-08-17T11:00:00',
    durationSeconds: 580,
    callType: 'VOICE',
    location: 'LOC005',
    tower: 'Metro CBD Tower South',
    source: 'Synthetic CDR Stream'
  },
  {
    id: 'CDR017',
    caller: 'P005',
    receiver: 'P008',
    callerPhone: 'PH005',
    receiverPhone: 'PH005',
    timestamp: '2026-08-17T14:30:00',
    durationSeconds: 190,
    callType: 'VOICE',
    location: 'LOC005',
    tower: 'Metro CBD Tower South',
    source: 'Synthetic CDR Stream'
  },
  {
    id: 'CDR018',
    caller: 'P001',
    receiver: 'P002',
    callerPhone: 'PH001',
    receiverPhone: 'PH002',
    timestamp: '2026-08-18T19:50:00',
    durationSeconds: 490,
    callType: 'VOICE',
    location: 'LOC001',
    tower: 'North Industrial Cell A-12',
    source: 'Synthetic CDR Stream'
  },
  {
    id: 'CDR019',
    caller: 'P005',
    receiver: 'P010',
    callerPhone: 'PH005',
    receiverPhone: 'PH008',
    timestamp: '2026-08-18T20:15:00',
    durationSeconds: 440,
    callType: 'VOICE',
    location: 'LOC005',
    tower: 'Metro CBD Tower North',
    source: 'Synthetic CDR Stream'
  },
  {
    id: 'CDR020',
    caller: 'P002',
    receiver: 'P006',
    callerPhone: 'PH002',
    receiverPhone: 'PH006',
    timestamp: '2026-08-19T07:45:00',
    durationSeconds: 320,
    callType: 'VOICE',
    location: 'LOC001',
    tower: 'North Industrial Cell B-04',
    source: 'Synthetic CDR Stream'
  },
  {
    id: 'CDR021',
    caller: 'P001',
    receiver: 'P004',
    callerPhone: 'PH001',
    receiverPhone: 'PH004',
    timestamp: '2026-08-20T11:20:00',
    durationSeconds: 275,
    callType: 'VOICE',
    location: 'LOC001',
    tower: 'North Industrial Cell A-12',
    source: 'Synthetic CDR Stream'
  },
  {
    id: 'CDR022',
    caller: 'P003',
    receiver: 'P002',
    callerPhone: 'PH003',
    receiverPhone: 'PH002',
    timestamp: '2026-08-21T18:10:00',
    durationSeconds: 660,
    callType: 'VOICE',
    location: 'LOC002',
    tower: 'Central Terminal Sector 2',
    source: 'Synthetic CDR Stream'
  },
  {
    id: 'CDR023',
    caller: 'P001',
    receiver: 'P002',
    callerPhone: 'PH001',
    receiverPhone: 'PH002',
    timestamp: '2026-08-22T02:15:00',
    durationSeconds: 380,
    callType: 'VOICE',
    location: 'LOC006',
    tower: 'Industrial Bypass Depot Cell',
    source: 'Synthetic CDR Stream'
  },
  {
    id: 'CDR024',
    caller: 'P006',
    receiver: 'P002',
    callerPhone: 'PH006',
    receiverPhone: 'PH002',
    timestamp: '2026-08-22T04:30:00',
    durationSeconds: 290,
    callType: 'VOICE',
    location: 'LOC006',
    tower: 'Industrial Bypass Depot Cell',
    source: 'Synthetic CDR Stream'
  },
  {
    id: 'CDR025',
    caller: 'P003',
    receiver: 'P005',
    callerPhone: 'PH003',
    receiverPhone: 'PH005',
    timestamp: '2026-08-23T10:40:00',
    durationSeconds: 520,
    callType: 'VOICE',
    location: 'LOC005',
    tower: 'Metro CBD Tower South',
    source: 'Synthetic CDR Stream'
  },
  {
    id: 'CDR026',
    caller: 'P010',
    receiver: 'P009',
    callerPhone: 'PH008',
    receiverPhone: 'PH005',
    timestamp: '2026-08-24T15:10:00',
    durationSeconds: 350,
    callType: 'VOICE',
    location: 'LOC005',
    tower: 'Metro CBD Tower North',
    source: 'Synthetic CDR Stream'
  },
  {
    id: 'CDR027',
    caller: 'P003',
    receiver: 'P001',
    callerPhone: 'PH003',
    receiverPhone: 'PH001',
    timestamp: '2026-08-25T19:55:00',
    durationSeconds: 710,
    callType: 'VOICE',
    location: 'LOC002',
    tower: 'Central Terminal Sector 1',
    source: 'Synthetic CDR Stream'
  },
  {
    id: 'CDR028',
    caller: 'P003',
    receiver: 'P002',
    callerPhone: 'PH003',
    receiverPhone: 'PH002',
    timestamp: '2026-08-25T20:15:00',
    durationSeconds: 640,
    callType: 'VOICE',
    location: 'LOC002',
    tower: 'Central Terminal Sector 1',
    source: 'Synthetic CDR Stream'
  },
  {
    id: 'CDR029',
    caller: 'P002',
    receiver: 'P001',
    callerPhone: 'PH002',
    receiverPhone: 'PH001',
    timestamp: '2026-08-25T20:35:00',
    durationSeconds: 530,
    callType: 'VOICE',
    location: 'LOC001',
    tower: 'North Industrial Cell A-12',
    source: 'Synthetic CDR Stream'
  },
  {
    id: 'CDR030',
    caller: 'P003',
    receiver: 'P005',
    callerPhone: 'PH003',
    receiverPhone: 'PH005',
    timestamp: '2026-08-25T21:10:00',
    durationSeconds: 490,
    callType: 'VOICE',
    location: 'LOC005',
    tower: 'Metro CBD Tower South',
    source: 'Synthetic CDR Stream'
  },
  {
    id: 'CDR031',
    caller: 'P005',
    receiver: 'P010',
    callerPhone: 'PH005',
    receiverPhone: 'PH008',
    timestamp: '2026-08-25T21:25:00',
    durationSeconds: 380,
    callType: 'VOICE',
    location: 'LOC005',
    tower: 'Metro CBD Tower North',
    source: 'Synthetic CDR Stream'
  },
  {
    id: 'CDR032',
    caller: 'P007',
    receiver: 'P004',
    callerPhone: 'PH007',
    receiverPhone: 'PH004',
    timestamp: '2026-08-27T16:50:00',
    durationSeconds: 160,
    callType: 'VOICE',
    location: 'LOC004',
    tower: 'Highland Pass Sector 2',
    source: 'Synthetic CDR Stream'
  },
  {
    id: 'CDR033',
    caller: 'P006',
    receiver: 'P002',
    callerPhone: 'PH006',
    receiverPhone: 'PH002',
    timestamp: '2026-08-28T06:45:00',
    durationSeconds: 240,
    callType: 'VOICE',
    location: 'LOC004',
    tower: 'Highland Pass Sector 1',
    source: 'Synthetic CDR Stream'
  },
  {
    id: 'CDR034',
    caller: 'P009',
    receiver: 'P005',
    callerPhone: 'PH005',
    receiverPhone: 'PH005',
    timestamp: '2026-09-01T14:20:00',
    durationSeconds: 295,
    callType: 'VOICE',
    location: 'LOC003',
    tower: 'Portview Dockside Base 4',
    source: 'Synthetic CDR Stream'
  },
  {
    id: 'CDR035',
    caller: 'P001',
    receiver: 'P002',
    callerPhone: 'PH001',
    receiverPhone: 'PH002',
    timestamp: '2026-09-03T21:40:00',
    durationSeconds: 470,
    callType: 'VOICE',
    location: 'LOC001',
    tower: 'North Industrial Cell A-12',
    source: 'Synthetic CDR Stream'
  },
  {
    id: 'CDR036',
    caller: 'P003',
    receiver: 'P001',
    callerPhone: 'PH003',
    receiverPhone: 'PH001',
    timestamp: '2026-09-04T18:15:00',
    durationSeconds: 530,
    callType: 'VOICE',
    location: 'LOC002',
    tower: 'Central Terminal Sector 2',
    source: 'Synthetic CDR Stream'
  },
  {
    id: 'CDR037',
    caller: 'P005',
    receiver: 'P010',
    callerPhone: 'PH005',
    receiverPhone: 'PH008',
    timestamp: '2026-09-05T11:35:00',
    durationSeconds: 410,
    callType: 'VOICE',
    location: 'LOC005',
    tower: 'Metro CBD Tower North',
    source: 'Synthetic CDR Stream'
  },
  {
    id: 'CDR038',
    caller: 'P003',
    receiver: 'P002',
    callerPhone: 'PH003',
    receiverPhone: 'PH002',
    timestamp: '2026-09-06T15:00:00',
    durationSeconds: 605,
    callType: 'VOICE',
    location: 'LOC002',
    tower: 'Central Terminal Sector 1',
    source: 'Synthetic CDR Stream'
  },
  {
    id: 'CDR039',
    caller: 'P002',
    receiver: 'P006',
    callerPhone: 'PH002',
    receiverPhone: 'PH006',
    timestamp: '2026-09-07T22:30:00',
    durationSeconds: 280,
    callType: 'VOICE',
    location: 'LOC001',
    tower: 'North Industrial Cell B-04',
    source: 'Synthetic CDR Stream'
  },
  {
    id: 'CDR040',
    caller: 'P001',
    receiver: 'P002',
    callerPhone: 'PH001',
    receiverPhone: 'PH002',
    timestamp: '2026-09-08T20:50:00',
    durationSeconds: 560,
    callType: 'VOICE',
    location: 'LOC001',
    tower: 'North Industrial Cell A-12',
    source: 'Synthetic CDR Stream'
  }
]

// ==========================================
// 4. SYNTHETIC EVIDENCE RECORDS (30+ ITEMS)
// ==========================================

export const evidenceRecords = [
  {
    id: 'EV001',
    type: 'CDR',
    title: 'Cellular Session CDR-2026-0811',
    source: 'Synthetel Telecom Log Database',
    date: '2026-08-11',
    reliability: 0.95,
    linkedEntities: ['P001', 'P002', 'PH001', 'PH002'],
    linkedRelationships: ['R001', 'R002', 'R003'],
    description: 'Synthetic telecommunications record confirming voice link of 420 seconds between P001 and P002.'
  },
  {
    id: 'EV002',
    type: 'INTELLIGENCE_NOTE',
    title: 'Device Subscriber Registration Profile',
    source: 'Synthetic Telecom Registry',
    date: '2026-06-12',
    reliability: 0.94,
    linkedEntities: ['P001', 'P002', 'PH001', 'PH002'],
    linkedRelationships: ['R002', 'R003'],
    description: 'Synthetic subscriber registration verification attaching PH001 to P001 and PH002 to P002.'
  },
  {
    id: 'EV003',
    type: 'LOCATION_RECORD',
    title: 'Tower Telemetry Ping Trail',
    source: 'Cellular Base Station Sector Logs',
    date: '2026-08-11',
    reliability: 0.92,
    linkedEntities: ['P002', 'PH002', 'LOC001'],
    linkedRelationships: ['R003', 'R016'],
    description: 'Synthetic radio handshake confirming PH002 continuous presence at North Sector Hub.'
  },
  {
    id: 'EV004',
    type: 'INTELLIGENCE_NOTE',
    title: 'Dispatch Order #NT-904',
    source: 'Warehouse Internal Audit',
    date: '2026-08-10',
    reliability: 0.88,
    linkedEntities: ['P001', 'P004', 'ORG001'],
    linkedRelationships: ['R004', 'R008'],
    description: 'Synthetic internal dispatch directive instructing terminal dock preparation.'
  },
  {
    id: 'EV005',
    type: 'INTELLIGENCE_NOTE',
    title: 'Haulage Loading Schedule #L-221',
    source: 'Central Terminal Dispatch Archive',
    date: '2026-08-12',
    reliability: 0.89,
    linkedEntities: ['P002', 'P004', 'LOC002'],
    linkedRelationships: ['R005', 'R017'],
    description: 'Synthetic bay allocation ledger co-signed by contractor P002 and supervisor P004.'
  },
  {
    id: 'EV006',
    type: 'CASE_RECORD',
    title: 'Corporate Consortium Registration #NS-884',
    source: 'Commercial Registrar of Companies',
    date: '2026-06-12',
    reliability: 0.96,
    linkedEntities: ['P001', 'P002', 'P004', 'P006', 'ORG001'],
    linkedRelationships: ['R006', 'R007', 'R008', 'R009'],
    description: 'Synthetic incorporation filing documenting Northstar Logistics key personnel.'
  },
  {
    id: 'EV007',
    type: 'INTELLIGENCE_NOTE',
    title: 'Inter-Agency Operational Review',
    source: 'Regional Cargo Task Force',
    date: '2026-08-12',
    reliability: 0.91,
    linkedEntities: ['P001', 'P002', 'ORG001'],
    linkedRelationships: ['R001', 'R007'],
    description: 'Synthetic multi-source assessment on command hierarchy and fleet decisions.'
  },
  {
    id: 'EV008',
    type: 'EVENT_RECORD',
    title: 'Convoy Alpha Radio Telemetry Manifest',
    source: 'Highway Patrol Highway Monitor',
    date: '2026-08-11',
    reliability: 0.93,
    linkedEntities: ['P001', 'P002', 'P006', 'VEH001', 'EVT001'],
    linkedRelationships: ['R010', 'R014', 'R023', 'R024', 'R025'],
    description: 'Synthetic radio logs placing vehicles and drivers in coordinated night haulage run.'
  },
  {
    id: 'EV009',
    type: 'CDR',
    title: 'Satellite Terminal Handshake Logs',
    source: 'AeroComm Telemetry Satellite Downlink',
    date: '2026-08-12',
    reliability: 0.89,
    linkedEntities: ['P006', 'PH006'],
    linkedRelationships: ['R011'],
    description: 'Synthetic transponder pings matching truck satellite unit PH006 with driver credentials.'
  },
  {
    id: 'EV010',
    type: 'VEHICLE_RECORD',
    title: 'Vehicle Registration Certificate UK07-TR-9182',
    source: 'State Motor Vehicle Department',
    date: '2026-06-08',
    reliability: 0.96,
    linkedEntities: ['P002', 'VEH001'],
    linkedRelationships: ['R012', 'R014'],
    description: 'Synthetic heavy multi-axle registration certificate issued under Rohit Sharma contractor permit.'
  },
  {
    id: 'EV011',
    type: 'VEHICLE_RECORD',
    title: 'Terminal Gate Pass DL05-VT-4410',
    source: 'North Hub Security Gate Records',
    date: '2026-08-11',
    reliability: 0.88,
    linkedEntities: ['P001', 'VEH002', 'LOC001'],
    linkedRelationships: ['R013', 'R015'],
    description: 'Synthetic automated RFID barcode capture authorizing DL05-VT-4410 entry.'
  },
  {
    id: 'EV012',
    type: 'LOCATION_RECORD',
    title: 'North Hub Biometric Access Logs',
    source: 'Automated Facility Security Server',
    date: '2026-08-11',
    reliability: 0.94,
    linkedEntities: ['P001', 'P002', 'LOC001'],
    linkedRelationships: ['R015', 'R016'],
    description: 'Synthetic turnstile biometric swipes within 12 minutes between P001 and P002.'
  },
  {
    id: 'EV013',
    type: 'EVENT_RECORD',
    title: 'Terminal Staging Meeting Minutes',
    source: 'Confidential Internal Memo',
    date: '2026-08-14',
    reliability: 0.92,
    linkedEntities: ['P001', 'P002', 'P003', 'P004', 'LOC002', 'EVT002'],
    linkedRelationships: ['R018', 'R019', 'R026', 'R027', 'R028', 'R036', 'R038'],
    description: 'Synthetic operational briefing record noting presence of P001, P002, P003, and P004.'
  },
  {
    id: 'EV014',
    type: 'FIR',
    title: 'Formal Complaint Copy FIR-2026-081',
    source: 'Central Police Station Registry',
    date: '2026-07-22',
    reliability: 0.97,
    linkedEntities: ['P001', 'P002', 'P004', 'CASE001'],
    linkedRelationships: ['R020', 'R021', 'R022'],
    description: 'Synthetic FIR document outlining cargo diversion along the northern transit route.'
  },
  {
    id: 'EV015',
    type: 'INTELLIGENCE_NOTE',
    title: 'Permit Verification Waybill Log',
    source: 'Highland State Transport Office',
    date: '2026-08-15',
    reliability: 0.82,
    linkedEntities: ['P004', 'P007'],
    linkedRelationships: ['R029'],
    description: 'Synthetic permit stamp requests submitted between liaison P007 and warehouse desk P004.'
  },
  {
    id: 'EV016',
    type: 'LOCATION_RECORD',
    title: 'Highland Weighbridge Pass Scan',
    source: 'Checkpost Optical Camera Archive',
    date: '2026-08-28',
    reliability: 0.86,
    linkedEntities: ['P007', 'LOC004'],
    linkedRelationships: ['R030'],
    description: 'Synthetic license plate and toll card capture identifying P007 vehicle at pass.'
  },
  {
    id: 'EV017',
    type: 'FIR',
    title: 'Transit Permit Investigation File #205',
    source: 'Highway Vigilance Cell Records',
    date: '2026-08-27',
    reliability: 0.89,
    linkedEntities: ['P007', 'CASE005'],
    linkedRelationships: ['R031'],
    description: 'Synthetic compliance file examining duplicate QR barcodes on commercial waybills.'
  },
  {
    id: 'EV018',
    type: 'CDR',
    title: 'Bridge Call Surge Analysis #CDR-B99',
    source: 'Telecom Analysis Extraction',
    date: '2026-08-16',
    reliability: 0.95,
    linkedEntities: ['P001', 'P002', 'P003', 'PH003'],
    linkedRelationships: ['R032', 'R033', 'R034'],
    description: 'Synthetic telephony extract revealing 14 calls from P003 bridging Northstar and financial agents.'
  },
  {
    id: 'EV019',
    type: 'CASE_RECORD',
    title: 'Commercial Commission Agreement #B-108',
    source: 'Arbitration Registry Repository',
    date: '2026-07-05',
    reliability: 0.91,
    linkedEntities: ['P002', 'P003'],
    linkedRelationships: ['R033'],
    description: 'Synthetic commission agreement detailing brokerage margins on inter-depot hauls.'
  },
  {
    id: 'EV020',
    type: 'INTELLIGENCE_NOTE',
    title: 'SIM Registration Profile PH003',
    source: 'Nexus Mobile Subscriber Database',
    date: '2026-06-15',
    reliability: 0.95,
    linkedEntities: ['P003', 'PH003'],
    linkedRelationships: ['R034'],
    description: 'Synthetic verified identification document linking handset PH003 to Sameer Khan.'
  },
  {
    id: 'EV021',
    type: 'VEHICLE_RECORD',
    title: 'Ownership Certificate UP14-FL-3309',
    source: 'State Transport Registration Authority',
    date: '2026-06-18',
    reliability: 0.94,
    linkedEntities: ['P003', 'VEH003'],
    linkedRelationships: ['R035'],
    description: 'Synthetic vehicle title document registering Utility Pickup to Sameer Khan.'
  },
  {
    id: 'EV022',
    type: 'CDR',
    title: 'Late-Hour Burst CDR Record Set',
    source: 'Synthetel Cell Station B-04',
    date: '2026-08-16',
    reliability: 0.92,
    linkedEntities: ['P001', 'P003'],
    linkedRelationships: ['R032'],
    description: 'Synthetic after-hours voice call records connecting P003 with P001.'
  },
  {
    id: 'EV023',
    type: 'EVENT_RECORD',
    title: 'Metro Plaza Executive Access Log',
    source: 'Tower B Building Management System',
    date: '2026-08-18',
    reliability: 0.94,
    linkedEntities: ['P003', 'P005', 'P010', 'LOC005', 'EVT003'],
    linkedRelationships: ['R037', 'R041', 'R054', 'R055', 'R060'],
    description: 'Synthetic visitor RFID badge captures during the Financial Settlement Session.'
  },
  {
    id: 'EV024',
    type: 'CDR',
    title: 'Surge Window Radio Monitor #SW-25',
    source: 'Automated Spectrum Monitor Cell',
    date: '2026-08-25',
    reliability: 0.96,
    linkedEntities: ['P001', 'P002', 'P003', 'P005', 'P010', 'EVT005'],
    linkedRelationships: ['R039'],
    description: 'Synthetic detection of 5 rapid cross-network calls within 90 minutes across clusters.'
  },
  {
    id: 'EV025',
    type: 'FIR',
    title: 'Investigation Order FIR-2026-104',
    source: 'Cyber & Telecom Inquiry Cell',
    date: '2026-08-05',
    reliability: 0.93,
    linkedEntities: ['P003', 'PH003', 'CASE002'],
    linkedRelationships: ['R040'],
    description: 'Synthetic case file exploring unauthorized telecommunication gateway usage.'
  },
  {
    id: 'EV026',
    type: 'FIR',
    title: 'Financial Irregularity Audit FIR-2026-139',
    source: 'Economic Offence Wing',
    date: '2026-08-14',
    reliability: 0.91,
    linkedEntities: ['P005', 'P010', 'CASE003'],
    linkedRelationships: ['R058', 'R059'],
    description: 'Synthetic forensic accounting report on irregular escrow credits.'
  },
  {
    id: 'EV027',
    type: 'CASE_RECORD',
    title: 'Blue Ridge Corporate Dossier #BR-01',
    source: 'Ministry of Corporate Affairs Archive',
    date: '2026-06-25',
    reliability: 0.96,
    linkedEntities: ['P003', 'P005', 'P009', 'P010', 'ORG002', 'ORG001'],
    linkedRelationships: ['R042', 'R044', 'R046', 'R049', 'R051', 'R064'],
    description: 'Synthetic corporate governance documents filed by Blue Ridge Traders Ltd.'
  },
  {
    id: 'EV028',
    type: 'CDR',
    title: 'Handset Echo Billing Extract',
    source: 'Metro Wireless Accounts Division',
    date: '2026-07-20',
    reliability: 0.92,
    linkedEntities: ['P005', 'PH005'],
    linkedRelationships: ['R043'],
    description: 'Synthetic statement showing encrypted voice subscriptions billed to P005.'
  },
  {
    id: 'EV029',
    type: 'CASE_RECORD',
    title: 'Apex Advisory Service Retainer',
    source: 'Commercial Contracts Registry',
    date: '2026-07-01',
    reliability: 0.90,
    linkedEntities: ['P005', 'P008', 'P010', 'ORG003'],
    linkedRelationships: ['R045', 'R047', 'R052', 'R053'],
    description: 'Synthetic corporate service agreement linking Apex executives and contractors.'
  },
  {
    id: 'EV030',
    type: 'VEHICLE_RECORD',
    title: 'Executive Fleet Permit HR26-SU-5501',
    source: 'State Executive Fleet Registration',
    date: '2026-06-30',
    reliability: 0.95,
    linkedEntities: ['P010', 'PH008', 'VEH005', 'EVT008'],
    linkedRelationships: ['R048', 'R057', 'R061'],
    description: 'Synthetic vehicle title and communications equipment assigned to Rajat Kapoor.'
  },
  {
    id: 'EV031',
    type: 'EVENT_RECORD',
    title: 'Port Customs Manifest & Weighbridge Record',
    source: 'Portview Bonded Warehouse Authority',
    date: '2026-09-02',
    reliability: 0.93,
    linkedEntities: ['P009', 'VEH004', 'LOC003', 'EVT007'],
    linkedRelationships: ['R056', 'R062', 'R063'],
    description: 'Synthetic cargo clearance log connecting P009 and Container Truck MH04-CT-8812.'
  },
  {
    id: 'EV032',
    type: 'INTELLIGENCE_NOTE',
    title: 'Hardware GPS Telemetry Extract',
    source: 'Asset Tracking Maintenance Portal',
    date: '2026-08-01',
    reliability: 0.88,
    linkedEntities: ['P008', 'P005'],
    linkedRelationships: ['R053'],
    description: 'Synthetic technical memo summarizing diagnostic reports submitted to finance desk.'
  }
]

// ==========================================
// 5. SYNTHETIC TIMELINE OBSERVATIONS
// ==========================================

export const timelineObservations = [
  {
    id: 'TL001',
    date: '2026-08-01',
    time: '10:00',
    eventType: 'EVIDENCE',
    title: 'Primary Cellular Lines Provisioned',
    description: 'Synthetic baseline registration of handsets PH001 and PH002 on northern networks.',
    entityId: 'P001',
    relatedEntityId: 'PH001',
    evidenceId: 'EV002',
    locationId: 'LOC001'
  },
  {
    id: 'TL002',
    date: '2026-08-05',
    time: '14:30',
    eventType: 'CASE',
    title: 'Case Registered: FIR-2026-104',
    description: 'Synthetic formal complaint filed regarding unauthorized telecommunication relay multiplexing.',
    entityId: 'CASE002',
    relatedEntityId: 'P003',
    evidenceId: 'EV025',
    locationId: 'LOC002'
  },
  {
    id: 'TL003',
    date: '2026-08-08',
    time: '09:00',
    eventType: 'OBSERVATION',
    title: 'Driver Team Hierarchy Operationalized',
    description: 'Synthetic field instruction placing driver leads under Rohit Sharma contractor supervision.',
    entityId: 'P006',
    relatedEntityId: 'P002',
    evidenceId: 'EV008',
    locationId: 'LOC001'
  },
  {
    id: 'TL004',
    date: '2026-08-10',
    time: '11:45',
    eventType: 'MEETING',
    title: 'Terminal Staging Dock Directive',
    description: 'Synthetic dispatch order #NT-904 communicated from P001 to warehouse supervisor P004.',
    entityId: 'P001',
    relatedEntityId: 'P004',
    evidenceId: 'EV004',
    locationId: 'LOC001'
  },
  {
    id: 'TL005',
    date: '2026-08-11',
    time: '21:14',
    eventType: 'CALL',
    title: 'Pre-Convoy Coordination Call',
    description: 'Synthetic 420-second voice consultation between Arjun Mehta and Rohit Sharma.',
    entityId: 'P001',
    relatedEntityId: 'P002',
    evidenceId: 'EV001',
    locationId: 'LOC001'
  },
  {
    id: 'TL006',
    date: '2026-08-11',
    time: '23:30',
    eventType: 'EVENT',
    title: 'Night Transport Convoy Initiated',
    description: 'Synthetic departure of 4 multi-axle rigs including UK07-TR-9182 under P006.',
    entityId: 'EVT001',
    relatedEntityId: 'VEH001',
    evidenceId: 'EV008',
    locationId: 'LOC001'
  },
  {
    id: 'TL007',
    date: '2026-08-12',
    time: '14:22',
    eventType: 'CALL',
    title: 'Dispatch Allocation Voice Order',
    description: 'Synthetic 540-second conference linking contractor P002 and depot supervisor P004.',
    entityId: 'P002',
    relatedEntityId: 'P004',
    evidenceId: 'EV005',
    locationId: 'LOC002'
  },
  {
    id: 'TL008',
    date: '2026-08-14',
    time: '11:30',
    eventType: 'CALL',
    title: 'Inter-City Broker Consultation',
    description: 'Synthetic call between Sameer Khan and Arjun Mehta prior to terminal briefing.',
    entityId: 'P003',
    relatedEntityId: 'P001',
    evidenceId: 'EV018',
    locationId: 'LOC002'
  },
  {
    id: 'TL009',
    date: '2026-08-14',
    time: '14:15',
    eventType: 'EVENT',
    title: 'Terminal Staging Meeting',
    description: 'Synthetic multi-subject assembly at Central Freight Terminal Yard C.',
    entityId: 'EVT002',
    relatedEntityId: 'P003',
    evidenceId: 'EV013',
    locationId: 'LOC002'
  },
  {
    id: 'TL010',
    date: '2026-08-14',
    time: '16:00',
    eventType: 'CASE',
    title: 'Financial Review Opened: FIR-2026-139',
    description: 'Synthetic case registration examining irregular escrow ledger accounts.',
    entityId: 'CASE003',
    relatedEntityId: 'P005',
    evidenceId: 'EV026',
    locationId: 'LOC005'
  },
  {
    id: 'TL011',
    date: '2026-08-15',
    time: '21:40',
    eventType: 'CALL',
    title: 'Transit Permit Barcode Inquiry',
    description: 'Synthetic phone exchange between supervisor P004 and permit liaison P007.',
    entityId: 'P004',
    relatedEntityId: 'P007',
    evidenceId: 'EV015',
    locationId: 'LOC002'
  },
  {
    id: 'TL012',
    date: '2026-08-16',
    time: '17:25',
    eventType: 'CALL',
    title: 'Cross-Network Broker Check-In',
    description: 'Synthetic voice contact between P001 and bridge broker P003.',
    entityId: 'P001',
    relatedEntityId: 'P003',
    evidenceId: 'EV022',
    locationId: 'LOC001'
  },
  {
    id: 'TL013',
    date: '2026-08-18',
    time: '16:45',
    eventType: 'EVENT',
    title: 'Financial Settlement Session',
    description: 'Synthetic meeting at Metro Plaza between P003, P005, and P010.',
    entityId: 'EVT003',
    relatedEntityId: 'P005',
    evidenceId: 'EV023',
    locationId: 'LOC005'
  },
  {
    id: 'TL014',
    date: '2026-08-20',
    time: '11:20',
    eventType: 'CALL',
    title: 'Auxiliary Depot Allocation Call',
    description: 'Synthetic voice consultation between Arjun Mehta and Vikram Joshi.',
    entityId: 'P001',
    relatedEntityId: 'P004',
    evidenceId: 'EV004',
    locationId: 'LOC001'
  },
  {
    id: 'TL015',
    date: '2026-08-22',
    time: '03:10',
    eventType: 'EVENT',
    title: 'Cargo Transfer at Industrial Depot',
    description: 'Synthetic offloading operation between Heavy Hauler and auxiliary vans at Depot 9B.',
    entityId: 'EVT004',
    relatedEntityId: 'VEH001',
    evidenceId: 'EV011',
    locationId: 'LOC006'
  },
  {
    id: 'TL016',
    date: '2026-08-25',
    time: '19:55',
    eventType: 'EVENT',
    title: 'High-Frequency Comms Spike Window',
    description: 'Synthetic surge of 5 rapid voice contacts linking both clusters within 90 minutes.',
    entityId: 'EVT005',
    relatedEntityId: 'P003',
    evidenceId: 'EV024',
    locationId: 'LOC002'
  },
  {
    id: 'TL017',
    date: '2026-08-27',
    time: '11:00',
    eventType: 'CASE',
    title: 'Transit Passes Inquiry: FIR-2026-205',
    description: 'Synthetic case initiated on counterfeit waybill barcodes at highway toll gates.',
    entityId: 'CASE005',
    relatedEntityId: 'P007',
    evidenceId: 'EV017',
    locationId: 'LOC004'
  },
  {
    id: 'TL018',
    date: '2026-08-28',
    time: '06:30',
    eventType: 'EVENT',
    title: 'Inter-State Highland Movement',
    description: 'Synthetic observation of transport convoy clearing Highland Checkpoint.',
    entityId: 'EVT006',
    relatedEntityId: 'VEH001',
    evidenceId: 'EV016',
    locationId: 'LOC004'
  },
  {
    id: 'TL019',
    date: '2026-09-02',
    time: '11:00',
    eventType: 'EVENT',
    title: 'Port Clearance Inspection',
    description: 'Synthetic bonded dock customs verification of Container Truck MH04-CT-8812.',
    entityId: 'EVT007',
    relatedEntityId: 'VEH004',
    evidenceId: 'EV031',
    locationId: 'LOC003'
  },
  {
    id: 'TL020',
    date: '2026-09-06',
    time: '17:30',
    eventType: 'EVENT',
    title: 'Executive Strategy Briefing',
    description: 'Synthetic governance assembly chaired by Rajat Kapoor at Metro Plaza.',
    entityId: 'EVT008',
    relatedEntityId: 'P010',
    evidenceId: 'EV030',
    locationId: 'LOC005'
  }
]

// ==========================================
// 6. SYNTHETIC LOCATION OVERLAP OBSERVATIONS
// ==========================================

export const locationObservations = [
  {
    id: 'LO001',
    locationId: 'LOC001',
    locationName: 'North Sector Warehouse Hub',
    observations: [
      { entityId: 'P001', count: 18, dateRange: '2026-08-01 to 2026-09-08' },
      { entityId: 'P002', count: 14, dateRange: '2026-08-01 to 2026-09-08' },
      { entityId: 'P006', count: 9, dateRange: '2026-08-11 to 2026-09-07' }
    ],
    overlaps: [
      { entityA: 'P001', entityB: 'P002', sharedDays: 12, overlapCount: 14 },
      { entityA: 'P001', entityB: 'P006', sharedDays: 7, overlapCount: 8 },
      { entityA: 'P002', entityB: 'P006', sharedDays: 8, overlapCount: 9 }
    ]
  },
  {
    id: 'LO002',
    locationId: 'LOC002',
    locationName: 'Central Freight Terminal',
    observations: [
      { entityId: 'P001', count: 9, dateRange: '2026-08-10 to 2026-09-04' },
      { entityId: 'P002', count: 11, dateRange: '2026-08-10 to 2026-09-06' },
      { entityId: 'P003', count: 12, dateRange: '2026-08-12 to 2026-09-06' },
      { entityId: 'P004', count: 22, dateRange: '2026-08-01 to 2026-09-08' }
    ],
    overlaps: [
      { entityA: 'P001', entityB: 'P003', sharedDays: 6, overlapCount: 7 },
      { entityA: 'P002', entityB: 'P003', sharedDays: 9, overlapCount: 11 },
      { entityA: 'P002', entityB: 'P004', sharedDays: 10, overlapCount: 11 },
      { entityA: 'P003', entityB: 'P004', sharedDays: 7, overlapCount: 8 }
    ]
  },
  {
    id: 'LO003',
    locationId: 'LOC005',
    locationName: 'Metro Plaza Office Complex',
    observations: [
      { entityId: 'P003', count: 5, dateRange: '2026-08-14 to 2026-09-05' },
      { entityId: 'P005', count: 16, dateRange: '2026-08-01 to 2026-09-08' },
      { entityId: 'P010', count: 14, dateRange: '2026-08-01 to 2026-09-08' }
    ],
    overlaps: [
      { entityA: 'P003', entityB: 'P005', sharedDays: 4, overlapCount: 5 },
      { entityA: 'P005', entityB: 'P010', sharedDays: 12, overlapCount: 13 }
    ]
  },
  {
    id: 'LO004',
    locationId: 'LOC004',
    locationName: 'Highland Transit Point',
    observations: [
      { entityId: 'P006', count: 4, dateRange: '2026-08-20 to 2026-08-28' },
      { entityId: 'P007', count: 6, dateRange: '2026-08-15 to 2026-08-28' }
    ],
    overlaps: [
      { entityA: 'P006', entityB: 'P007', sharedDays: 2, overlapCount: 3 }
    ]
  }
]

// ==========================================
// 7. PATTERN DETECTION RULES (DEMO RULEBASE)
// ==========================================

export const patternRuleDefinitions = [
  {
    id: 'RULE_FREQ_COMMS',
    name: 'Repeated Communication Frequency',
    category: 'COMMUNICATION',
    description: 'High frequency of voice calls (>5 interactions within the observation window).',
    confidenceBase: 0.88,
    severity: 'HIGH'
  },
  {
    id: 'RULE_SHARED_LOC',
    name: 'Observed Spatial Overlap',
    category: 'LOCATION',
    description: 'Multiple subjects recorded at the same physical hub within identical time intervals.',
    confidenceBase: 0.85,
    severity: 'MEDIUM'
  },
  {
    id: 'RULE_BRIDGE_ENTITY',
    name: 'Cross-Network Bridge Entity',
    category: 'TOPOLOGY',
    description: 'Subject connects otherwise separate operational clusters with high betweenness centrality.',
    confidenceBase: 0.92,
    severity: 'HIGH'
  },
  {
    id: 'RULE_COMMS_SPIKE',
    name: 'Telecommunication Surge Window',
    category: 'TEMPORAL',
    description: 'Rapid succession of voice interactions across multiple handsets during key event windows.',
    confidenceBase: 0.90,
    severity: 'HIGH'
  },
  {
    id: 'RULE_CASE_COMMS',
    name: 'Case-Linked Communication Pattern',
    category: 'LEGAL',
    description: 'Communication between parties with concurrent involvement in formal case dossiers.',
    confidenceBase: 0.86,
    severity: 'HIGH'
  },
  {
    id: 'RULE_CROSS_CLUSTER',
    name: 'Cross-Cluster Intermediation',
    category: 'TOPOLOGY',
    description: 'Active financial and transport linkages between separate organizational consortia.',
    confidenceBase: 0.89,
    severity: 'MEDIUM'
  },
  {
    id: 'RULE_NIGHT_ACTIVITY',
    name: 'Late-Hour Operational Activity',
    category: 'TEMPORAL',
    description: 'High concentration of vehicle movement and calls observed between 20:00 and 05:00.',
    confidenceBase: 0.82,
    severity: 'MEDIUM'
  },
  {
    id: 'RULE_VEHICLE_SHARING',
    name: 'Multi-Subject Vehicle Association',
    category: 'ASSET',
    description: 'Commercial vehicle operated or authorized by multiple distinct subjects.',
    confidenceBase: 0.87,
    severity: 'MEDIUM'
  },
  {
    id: 'RULE_EVENT_WINDOW',
    name: 'Multi-Subject Event Convergence',
    category: 'EVENT',
    description: 'Simultaneous presence of multiple key entities during organized event timelines.',
    confidenceBase: 0.91,
    severity: 'HIGH'
  },
  {
    id: 'RULE_HIGH_CENTRALITY',
    name: 'High-Degree Hub Entity',
    category: 'TOPOLOGY',
    description: 'Subject maintaining greater than 6 direct heterogeneous relationships.',
    confidenceBase: 0.84,
    severity: 'MEDIUM'
  }
]
